import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <nav className="navigation">
            <ul className="lista">
              <li><a href="/hosting">Hosting</a></li>
              <li><a href="/domain" >Domain</a></li>
              <li><a href="/features">Features</a></li>
              <li><a href="/support">Support</a></li>
              <li><a href="/community">Community</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}

