import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <header>
        <nav className="navigation">
          <ul className="lista">
            <li><a href="/hosting" className="hover:underline">Hosting</a></li>
            <li><a href="/domain" className="hover:underline">Domain</a></li>
            <li><a href="/features" className="hover:underline">Features</a></li>
            <li><a href="/support" className="hover:underline">Support</a></li>
            <li><a href="/community" className="hover:underline">Community</a></li>
          </ul>
        </nav>
        </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
